# Generated by Django 3.2.3 on 2021-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create_at', models.DateField(auto_created=True)),
                ('user_name', models.CharField(max_length=32)),
                ('user_password', models.CharField(max_length=32)),
                ('is_active', models.CharField(choices=[('1', 'yes'), ('0', 'no')], default=0, max_length=5)),
                ('user_power', models.CharField(choices=[('1', 'supper'), ('2', 'common')], max_length=5)),
            ],
        ),
    ]
