# Generated by Django 3.2.3 on 2021-05-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_ip', models.GenericIPAddressField(unique=True)),
                ('work_or_no', models.CharField(choices=[(0, 'inactive'), (1, 'active')], max_length=2)),
                ('remark', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Node_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32)),
                ('use_node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.node', to_field='node_ip')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.user', to_field='user_name')),
            ],
        ),
    ]
