# Generated by Django 3.2.3 on 2021-06-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210526_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=2),
        ),
        migrations.AlterField(
            model_name='node_group',
            name='use_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.node', to_field='node_ip'),
        ),
        migrations.AlterField(
            model_name='node_group',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.group', to_field='group_name'),
        ),
    ]
