# Generated by Django 3.2.3 on 2021-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_group_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node_group',
            old_name='group_name',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='node_group',
            old_name='use_node',
            new_name='Node',
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], max_length=2),
        ),
    ]
