# Generated by Django 3.2.3 on 2021-06-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210604_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name_plural': '操作'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterModelOptions(
            name='page_actions',
            options={'verbose_name_plural': '页面权限表'},
        ),
        migrations.AlterModelOptions(
            name='role_page_actions',
            options={'verbose_name_plural': '角色权限表'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_power',
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], max_length=2),
        ),
    ]
