# Generated by Django 3.2.3 on 2021-06-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210607_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page_Actions',
            new_name='Page2Actions',
        ),
        migrations.RenameModel(
            old_name='Role_Page_Actions',
            new_name='Role2Page2Actions',
        ),
        migrations.RenameModel(
            old_name='User_Role',
            new_name='User2Role',
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=2),
        ),
    ]
