# Generated by Django 3.2.3 on 2021-06-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_node_work_or_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
    ]
