# Generated by Django 3.2.3 on 2021-06-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20210607_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], max_length=2),
        ),
        migrations.CreateModel(
            name='Menu2Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.menu')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.pages')),
            ],
        ),
    ]
