# Generated by Django 3.2.3 on 2021-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20210615_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], max_length=2),
        ),
    ]
