# Generated by Django 3.2.3 on 2021-06-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20210615_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt', models.TextField()),
                ('key', models.TextField()),
                ('contain_domain', models.TextField()),
                ('expired_time', models.DateField()),
            ],
        ),
    ]
