# Generated by Django 3.2.3 on 2021-07-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(max_length=256, unique=True)),
                ('alias', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cname_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cname', to_field='cname')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.group')),
            ],
        ),
        migrations.AddField(
            model_name='cname',
            name='ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.nameserver', to_field='ns'),
        ),
    ]
