# Generated by Django 3.2.3 on 2021-07-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20210705_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameserver',
            name='ns',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='work_or_no',
            field=models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=2),
        ),
    ]
