# Generated by Django 3.2.3 on 2021-07-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20210705_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDomain_Src',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_head', models.CharField(max_length=32)),
                ('use_src', models.CharField(max_length=256)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Domain_Cname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.cname')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.domain')),
            ],
        ),
    ]
