# Generated by Django 3.2.3 on 2021-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_domain_cname_subdomain_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain_src',
            name='protocol',
            field=models.CharField(choices=[('4', 'wss'), ('1', 'http'), ('3', 'ws'), ('2', 'https')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
